setup dynamodb utils scripts

diff --git a/backend-flask/bin/ddb/list-tables b/backend-flask/bin/ddb/list-tables
--- a/backend-flask/bin/ddb/list-tables
+++ b/backend-flask/bin/ddb/list-tables
@@ -1,7 +1,11 @@
 #! /usr/bin/bash
 
-if ["$1" = "prod"]; then
-    ENDPOINT_URL = ""
+set -e #stop if it fails at any point
+
+if [ "$1" = "prod" ]; then
+    ENDPOINT_URL=""
 else
-    ENDPOINT_URL = "--endpoint-url=http://localhost:8000"
+    ENDPOINT_URL="--endpoint-url=http://localhost:8000"
 fi
+
+aws dynamodb list-tables $ENDPOINT_URL --query TableNames --output table
